swagger: '2.0'
info:
  title: Cloud Endpoints + Cloud Run
  description: Sample API on Cloud Endpoints with a Cloud Run backend
  version: 1.0.0
host: gateway-pfst5brwxq-uc.a.run.app
schemes:
  - https
produces:
  - application/json
security: []
x-google-backend:
  address: https://rockimage-integration-pfst5brwxq-uc.a.run.app
  protocol: h2
paths:
  /:
    get:
      summary: Root
      operationId: root
      responses:
        '200':
          description: A successful response
          schema:
            type: string

  /images:
    get:
      summary: Gets UUIDS of all images
      operationId: images
      responses:
        '200':
          description: A successful response
          schema:
            type: array
            items:
              type: object
              properties:
                uuid:
                  type: string
                  description: The UUID.
                path:
                  type: string
                  description: The path of the image.

    post:
      operationId: create
      summary: Uploads an image.
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: file
          type: string
          format: binary
          description: The file to upload.
      responses:
        '200':
          description: A successful response
          schema:
            type: object
            properties:
              uuid:
                type: string
                description: The UUID.
              path:
                type: string
                description: The path of the image.

  /images/{uuid}:
    get:
      operationId: single-image
      summary: Get a user by ID
      parameters:
      - name: uuid
        in: "path"
        description: "ID of pet to return"
        required: true
        type: string
      responses:
        '200':
          description: A successful response
          schema:
            type: object
            properties:
              uuid:
                type: string
                description: The UUID.
              path:
                type: string
                description: The path of the image.
