"""annotations

Revision ID: 9c530297ce7f
Revises: a2169b8e8dec
Create Date: 2020-10-01 11:50:39.516949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c530297ce7f'
down_revision = 'a2169b8e8dec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('annotations', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'annotations')
    # ### end Alembic commands ###
